### PR TITLE
Support for contracts, tokens

### PR DESCRIPTION
**Pull request by bsh98**
Adds support for exporting contracts and tokens tables.

The relevant streaming changes can be found here https://github.com/blockchain-etl/ethereum-etl/pull/293.

### CODE REVIEW

**Comment by whydna** [comment]
@bsh98 awesome - does the current version not support contracts? Will this change work seamlessly if I've already run an export against the current version? Any idea when this PR will be ready/merged?

**Comment by bsh98** [comment]
> @bsh98 awesome - does the current version not support contracts? Will this change work seamlessly if I've already run an export against the current version? Any idea when this PR will be ready/merged?

No, the current version does not support contracts.  And yes, this should work no problem if you've already run the current version.  The PR should be ready, but unfortunately I don't have an estimate on when it will be merged.  (It looks like there hasn't been much activity on this repo recently)

**Comment by medvedev1088** [comment]
Thanks for the PR @bsh98 !

**Comment by medvedev1088** [comment]
This index will prevent loading historical contracts since there are contract deployed multiple times in the same block `alter table contracts add constraint contracts_pk primary key (address, block_number);` as discovered by a user https://t.me/c/1190882423/1504

Eugene Hsu, [24 Apr 2022 at 4:57:18 PM]:
Hello guys

I'm using ethereum-etl-postgres (https://github.com/blockchain-etl/ethereum-etl-postgres) to fetch contracts data, and found there are some duplicate records in the data source, is there anyone encounter the same problem?

data source is: bigquery > bigquery-public-data.crypto_ethereum.contracts

I found a duplicate records through sql below, and there are more records like this:

SELECT * FROM bigquery-public-data.crypto_ethereum.contracts WHERE address = '0x21e89b517469604e7ea9f564c45ef33d512fff9d' AND block_number = 9391097

**Pull request merged**
